# Generated by Django 6.0.3 on 2026-04-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("can_unpublish_product", "Может отменять публикацию продукта"),
                ),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликован")],
                default="draft",
                max_length=10,
                verbose_name="Статус публикации",
            ),
        ),
    ]
